export { deleteProcessAction } from './mutations/delete-process.action'
export { insertProcessAction } from './mutations/insert-process.action'
export { updateProcessAction } from './mutations/update-process.action'
export * from './queries/query-process-by-id.action'
export * from './queries/query-processes.action'
