services:
  db:
    image: supabase/postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  api:
    image: supabase/gotrue:latest
    environment:
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_URL: postgres://postgres:postgres@db:5432/postgres
    ports:
      - "9999:9999"

