import './globals.css'

import type { Metadata } from 'next'
import { Providers } from '@/components/providers'
import { fontFamily } from '@/config/font-family'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="pt-BR" suppressHydrationWarning>
			<body className={`${fontFamily} antialiased`}>
				<Providers>{children}</Providers>
			</body>
		</html>
	)
}
